### ISSUE TITLE
Отмена НДС

### ISSUE THREAD

**Issue by ssitdikov** [klkvsk/beeline-ord-api-client#1]
В связи с новыми изменениями - isVat теперь необязательно вроде как и возвращается null?

**Comment by klkvsk** [comment]
Библиотека отстала от актуальной версии апи. Текущая версия 1.43 относится к v43 спецификации. 
Не уверен, что смогу в ближайшее время пройтись по изменениям и добавить их все. Так что пулл-реквесты приветствуются.

**Comment by klkvsk** [comment]
обновлено isVat, добавлены exportedStatus, exportError
